# Basic Information 
title: Daniel Rodriguez-Cardenas
position: Ph.D. Student
affiliation: William & Mary, USA 
affiliation_link: 
affiliation_logo: 
email: dhrodriguezcar (at) wm.edu
email2: danielrcardenas (at) gmail.com

# Search Engine Optimization (SEO)
keywords: Daniel Rodriguez, Daniel Rodriguez-Cardenas
canonical: 
description: Daniel Rodriguez-Cardenas is a Ph.D. student at William & Mary, USA. His primary research interests lie in software evolution, AI4SE, interpretability, causal analysis. 

# The option is used to enable the Johns Hopkins template.
enable_hopkins_logo: true

# The option is used to show the last update time.
enable_last_update: false

# Links
link_type: icon #text/icon
google_scholar: https://scholar.google.com/citations?user=4DbuyrgAAAAJ&hl=en&authuser=1
github_link: https://github.com/danielrcardenas
linkedin: https://www.linkedin.com/in/daniel-rodriguez-cardenas/
cv_link: 

# Images 
avatar: ./assets/img/profile.jpg
favicon: 
favicon_dark: 

# Footnotes
footnote: 
footnote_link: 

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
clustrmaps_id: 

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
